export enum Denomination {
  NON_DENOMINATIONAL = 'NON_DENOMINATIONAL',
  BAPTIST = 'BAPTIST',
  METHODIST = 'METHODIST',
  PRESBYTERIAN = 'PRESBYTERIAN',
  PENTECOSTAL = 'PENTECOSTAL',
  LUTHERAN = 'LUTHERAN',
  EPISCOPAL = 'EPISCOPAL',
  OTHER = 'OTHER',
}
