export enum Department {
  SOUND_TRYBE = 'SOUND_TRYBE',
  USHERING_GREETERS_PROTOCOL = 'USHERING/GREETERS/PROTOCOL',
  PRAYER_BIBLE_STUDY = 'PRAYER/BIBLE_STUDY',
  PUBLICITY_OUTREACH = 'PUBLICITY/OUTREACH',
  PROGRAMS = 'PROGRAMS',
  MEDIA_TECHNICAL = 'MEDIA/TECHNICAL',
  PROGRAMS_VENUE_MANAGEMENT = 'PROGRAMS/VENUE_MANAGEMENT',
  MEMBERSHIP = 'MEMBERSHIP',
  WELFARE_HOSPITALITY = 'WELFARE/HOSPITALITY',
}
