export enum OrganizationRole {
  SENIOR_PASTOR = 'SENIOR_PASTOR',
  ASSOCIATE_PASTOR = 'ASSOCIATE_PASTOR',
  YOUTH_PASTOR = 'YOUTH_PASTOR',
  WORSHIP_LEADER = 'WORSHIP_LEADER',
  CHURCH_ADMIN = 'CHURCH_ADMIN',
  VOLUNTEER_LEADER = 'VOLUNTEER_LEADER',
  OTHER = 'OTHER',
}
