export const TEMPLATE_PRESETS = [
  {
    name: 'WhatsApp — First Visit Welcome',
    channel: 'whatsapp',
    trigger: 'on_registration',
    body: "Hi {{name}}! 🎉 Welcome to {{church_name}}! We're so glad you joined us today. Our doors are always open for you. We'd love to see you again this Sunday! 🙏",
    variables: ['name', 'church_name'],
    isPreset: true,
    isActive: true,
    organizationId: null,
  },
  {
    name: 'WhatsApp — Day 3 Follow-up',
    channel: 'whatsapp',
    trigger: 'day_3',
    body: "Hello {{name}}! It's been 3 days since your visit to {{church_name}}. We hope you felt at home 😊 We'd love to answer any questions you have — feel free to reply to this message anytime. Looking forward to seeing you again!",
    variables: ['name', 'church_name'],
    isPreset: true,
    isActive: true,
    organizationId: null,
  },
  {
    name: 'WhatsApp — Day 7 Follow-up',
    channel: 'whatsapp',
    trigger: 'day_7',
    body: "Hi {{name}}! It's been a week since you visited {{church_name}} and we haven't forgotten about you 🙌 You're always welcome here. Join us this Sunday — we'd love to have you back!",
    variables: ['name', 'church_name'],
    isPreset: true,
    isActive: true,
    organizationId: null,
  },
  {
    name: 'SMS — First Visit Welcome',
    channel: 'sms',
    trigger: 'on_registration',
    body: 'Hi {{name}}, welcome to {{church_name}}! We were blessed to have you worship with us. We hope to see you again soon! Reply STOP to opt out.',
    variables: ['name', 'church_name'],
    isPreset: true,
    isActive: true,
    organizationId: null,
  },
  {
    name: 'SMS — Day 3 Follow-up',
    channel: 'sms',
    trigger: 'day_3',
    body: "Hi {{name}}! {{church_name}} here. Hope you're doing well. We'd love to have you back this Sunday! Reply STOP to opt out.",
    variables: ['name', 'church_name'],
    isPreset: true,
    isActive: true,
    organizationId: null,
  },
  {
    name: 'Manual — General Thank You',
    channel: 'whatsapp',
    trigger: 'manual',
    body: 'Dear {{name}}, thank you for visiting {{church_name}} on {{service_date}}. It was a blessing having you with us. We hope to see you again soon! God bless you 🙏',
    variables: ['name', 'church_name', 'service_date'],
    isPreset: true,
    isActive: true,
    organizationId: null,
  },
];
